//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.13 at 10:34:00 PM PDT 
//


package edu.nps.moves.siso.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="revisions" type="{}revisions_t"/>
 *         &lt;element name="acronyms" type="{}acronyms_t"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="enum" type="{}enum_t" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="bitmask" type="{}bitmask_t" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="cet" type="{}cet_t" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="cot" type="{}cot_t" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="record" type="{}record_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="release" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="organisation" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "revisions",
    "acronyms",
    "enumOrBitmaskOrCet"
})
@XmlRootElement(name = "ebv")
public class Ebv {

    @XmlElement(required = true)
    protected RevisionsT revisions;
    @XmlElement(required = true)
    protected AcronymsT acronyms;
    @XmlElements({
        @XmlElement(name = "cot", type = CotT.class),
        @XmlElement(name = "enum", type = EnumT.class),
        @XmlElement(name = "cet", type = CetT.class),
        @XmlElement(name = "bitmask", type = BitmaskT.class),
        @XmlElement(name = "record", type = RecordT.class)
    })
    protected List<GenerictableT> enumOrBitmaskOrCet;
    @XmlAttribute(required = true)
    protected String title;
    @XmlAttribute(required = true)
    protected String release;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlAttribute(required = true)
    protected String href;
    @XmlAttribute(required = true)
    protected String organisation;

    /**
     * Gets the value of the revisions property.
     * 
     * @return
     *     possible object is
     *     {@link RevisionsT }
     *     
     */
    public RevisionsT getRevisions() {
        return revisions;
    }

    /**
     * Sets the value of the revisions property.
     * 
     * @param value
     *     allowed object is
     *     {@link RevisionsT }
     *     
     */
    public void setRevisions(RevisionsT value) {
        this.revisions = value;
    }

    /**
     * Gets the value of the acronyms property.
     * 
     * @return
     *     possible object is
     *     {@link AcronymsT }
     *     
     */
    public AcronymsT getAcronyms() {
        return acronyms;
    }

    /**
     * Sets the value of the acronyms property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcronymsT }
     *     
     */
    public void setAcronyms(AcronymsT value) {
        this.acronyms = value;
    }

    /**
     * Gets the value of the enumOrBitmaskOrCet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enumOrBitmaskOrCet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnumOrBitmaskOrCet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CotT }
     * {@link EnumT }
     * {@link CetT }
     * {@link BitmaskT }
     * {@link RecordT }
     * 
     * 
     */
    public List<GenerictableT> getEnumOrBitmaskOrCet() {
        if (enumOrBitmaskOrCet == null) {
            enumOrBitmaskOrCet = new ArrayList<GenerictableT>();
        }
        return this.enumOrBitmaskOrCet;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the release property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelease() {
        return release;
    }

    /**
     * Sets the value of the release property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelease(String value) {
        this.release = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the organisation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganisation() {
        return organisation;
    }

    /**
     * Sets the value of the organisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganisation(String value) {
        this.organisation = value;
    }

}
