#include <sstream>
#include <cstddef>
#include <disenum/DatumSpecificationRecord.h>

namespace DIS {


hashMap<int,DatumSpecificationRecord*> DatumSpecificationRecord::enumerations;

DatumSpecificationRecord DatumSpecificationRecord::IDENTIFICATION(10000, "Identification");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_TYPE(11000, "Entity Type");
DatumSpecificationRecord DatumSpecificationRecord::CONCATENATED(11100, "Concatenated");
DatumSpecificationRecord DatumSpecificationRecord::KIND(11110, "Kind");
DatumSpecificationRecord DatumSpecificationRecord::DOMAIN(11120, "Domain");
DatumSpecificationRecord DatumSpecificationRecord::COUNTRY(11130, "Country");
DatumSpecificationRecord DatumSpecificationRecord::CATEGORY(11140, "Category");
DatumSpecificationRecord DatumSpecificationRecord::SUBCATEGORY(11150, "Subcategory");
DatumSpecificationRecord DatumSpecificationRecord::SPECIFIC(11160, "Specific");
DatumSpecificationRecord DatumSpecificationRecord::EXTRA(11170, "Extra");
DatumSpecificationRecord DatumSpecificationRecord::FORCE_ID(11200, "Force ID");
DatumSpecificationRecord DatumSpecificationRecord::DESCRIPTION(11300, "Description");
DatumSpecificationRecord DatumSpecificationRecord::ALTERNATIVE_ENTITY_TYPE(12000, "Alternative Entity Type");
DatumSpecificationRecord DatumSpecificationRecord::KIND_1(12110, "Kind");
DatumSpecificationRecord DatumSpecificationRecord::DOMAIN_2(12120, "Domain");
DatumSpecificationRecord DatumSpecificationRecord::COUNTRY_3(12130, "Country");
DatumSpecificationRecord DatumSpecificationRecord::CATEGORY_4(12140, "Category");
DatumSpecificationRecord DatumSpecificationRecord::SUBCATEGORY_5(12150, "Subcategory");
DatumSpecificationRecord DatumSpecificationRecord::SPECIFIC_6(12160, "Specific");
DatumSpecificationRecord DatumSpecificationRecord::EXTRA_7(12170, "Extra");
DatumSpecificationRecord DatumSpecificationRecord::DESCRIPTION_8(12300, "Description");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_MARKING(13000, "Entity Marking");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_MARKING_CHARACTERS(13100, "Entity Marking Characters");
DatumSpecificationRecord DatumSpecificationRecord::CREW_ID(13200, "Crew ID");
DatumSpecificationRecord DatumSpecificationRecord::TASK_ORGANIZATION(14000, "Task Organization");
DatumSpecificationRecord DatumSpecificationRecord::REGIMENT_NAME(14200, "Regiment Name");
DatumSpecificationRecord DatumSpecificationRecord::BATTALION_NAME(14300, "Battalion Name");
DatumSpecificationRecord DatumSpecificationRecord::COMPANY_NAME(14400, "Company Name");
DatumSpecificationRecord DatumSpecificationRecord::PLATOON_NAME(14500, "Platoon Name");
DatumSpecificationRecord DatumSpecificationRecord::SQUAD_NAME(14520, "Squad Name");
DatumSpecificationRecord DatumSpecificationRecord::TEAM_NAME(14540, "Team Name");
DatumSpecificationRecord DatumSpecificationRecord::BUMPER_NUMBER(14600, "Bumper Number");
DatumSpecificationRecord DatumSpecificationRecord::VEHICLE_NUMBER(14700, "Vehicle Number");
DatumSpecificationRecord DatumSpecificationRecord::UNIT_NUMBER(14800, "Unit Number");
DatumSpecificationRecord DatumSpecificationRecord::DIS_IDENTITY(15000, "DIS Identity");
DatumSpecificationRecord DatumSpecificationRecord::DIS_SITE_ID(15100, "DIS Site ID");
DatumSpecificationRecord DatumSpecificationRecord::DIS_HOST_ID(15200, "DIS Host ID");
DatumSpecificationRecord DatumSpecificationRecord::DIS_ENTITY_ID(15300, "DIS Entity ID");
DatumSpecificationRecord DatumSpecificationRecord::MOUNT_INTENT(15400, "Mount Intent");
DatumSpecificationRecord DatumSpecificationRecord::TETHER_UNTHETHER_COMMAND_ID(15500, "Tether-Unthether Command ID");
DatumSpecificationRecord DatumSpecificationRecord::TELEPORT_ENTITY_DATA_RECORD(15510, "Teleport Entity Data Record");
DatumSpecificationRecord DatumSpecificationRecord::DIS_AGGREGATE_ID_SET_IF_COMMUNICATION_TO_AGGREGATE(15600, "DIS Aggregate ID (Set if communication to aggregate)");
DatumSpecificationRecord DatumSpecificationRecord::LOADS(20000, "Loads");
DatumSpecificationRecord DatumSpecificationRecord::CREW_MEMBERS(21000, "Crew Members");
DatumSpecificationRecord DatumSpecificationRecord::CREW_MEMBER_ID(21100, "Crew Member ID");
DatumSpecificationRecord DatumSpecificationRecord::HEALTH(21200, "Health");
DatumSpecificationRecord DatumSpecificationRecord::JOB_ASSIGNMENT(21300, "Job Assignment");
DatumSpecificationRecord DatumSpecificationRecord::FUEL(23000, "Fuel");
DatumSpecificationRecord DatumSpecificationRecord::QUANTITY(23100, "Quantity");
DatumSpecificationRecord DatumSpecificationRecord::QUANTITY_9(23105, "Quantity");
DatumSpecificationRecord DatumSpecificationRecord::AMMUNITION(24000, "Ammunition");
DatumSpecificationRecord DatumSpecificationRecord::X_120_MM_HEAT_QUANTITY(24001, "120-mm HEAT, quantity");
DatumSpecificationRecord DatumSpecificationRecord::X_120_MM_SABOT_QUANTITY(24002, "120-mm SABOT, quantity");
DatumSpecificationRecord DatumSpecificationRecord::X_127_MM_M8_QUANTITY(24003, "12.7-mm M8, quantity");
DatumSpecificationRecord DatumSpecificationRecord::X_127_MM_M20_QUANTITY(24004, "12.7-mm M20, quantity");
DatumSpecificationRecord DatumSpecificationRecord::X_762_MM_M62_QUANTITY(24005, "7.62-mm M62, quantity");
DatumSpecificationRecord DatumSpecificationRecord::M250_UKL8A1_QUANTITY(24006, "M250 UKL8A1, quantity");
DatumSpecificationRecord DatumSpecificationRecord::M250_UKL8A3_QUANTITY(24007, "M250 UKL8A3, quantity");
DatumSpecificationRecord DatumSpecificationRecord::X_762_MM_M80_QUANTITY(24008, "7.62-mm M80, quantity");
DatumSpecificationRecord DatumSpecificationRecord::X_127_MM_QUANTITY(24009, "12.7-mm, quantity");
DatumSpecificationRecord DatumSpecificationRecord::X_762_MM_QUANTITY(24010, "7.62-mm, quantity");
DatumSpecificationRecord DatumSpecificationRecord::MINES_QUANTITY(24060, "Mines, quantity");
DatumSpecificationRecord DatumSpecificationRecord::TYPE(24100, "Type");
DatumSpecificationRecord DatumSpecificationRecord::KIND_10(24110, "Kind");
DatumSpecificationRecord DatumSpecificationRecord::DOMAIN_11(24120, "Domain");
DatumSpecificationRecord DatumSpecificationRecord::COUNTRY_12(24130, "Country");
DatumSpecificationRecord DatumSpecificationRecord::CATEGORY_13(24140, "Category");
DatumSpecificationRecord DatumSpecificationRecord::SUBCATEGORY_14(24150, "Subcategory");
DatumSpecificationRecord DatumSpecificationRecord::EXTRA_15(24160, "Extra");
DatumSpecificationRecord DatumSpecificationRecord::DESCRIPTION_16(24300, "Description");
DatumSpecificationRecord DatumSpecificationRecord::CARGO(25000, "Cargo");
DatumSpecificationRecord DatumSpecificationRecord::VEHICLE_MASS(26000, "Vehicle Mass");
DatumSpecificationRecord DatumSpecificationRecord::SUPPLY_QUANTITY(27000, "Supply Quantity");
DatumSpecificationRecord DatumSpecificationRecord::ARMAMENT(28000, "Armament");
DatumSpecificationRecord DatumSpecificationRecord::STATUS(30000, "Status");
DatumSpecificationRecord DatumSpecificationRecord::ACTIVATE_ENTITY(30010, "Activate entity");
DatumSpecificationRecord DatumSpecificationRecord::SUBSCRIPTION_STATE(30100, "Subscription State");
DatumSpecificationRecord DatumSpecificationRecord::ROUND_TRIP_TIME_DELAY(30300, "Round trip time delay");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_0(30400, "TADIL J message count (label 0)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_1(30401, "TADIL J message count (label 1)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_2(30402, "TADIL J message count (label 2)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_3(30403, "TADIL J message count (label 3)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_4(30404, "TADIL J message count (label 4)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_5(30405, "TADIL J message count (label 5)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_6(30406, "TADIL J message count (label 6)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_7(30407, "TADIL J message count (label 7)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_8(30408, "TADIL J message count (label 8)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_9(30409, "TADIL J message count (label 9)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_10(30410, "TADIL J message count (label 10)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_11(30411, "TADIL J message count (label 11)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_12(30412, "TADIL J message count (label 12)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_13(30413, "TADIL J message count (label 13)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_14(30414, "TADIL J message count (label 14)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_15(30415, "TADIL J message count (label 15)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_16(30416, "TADIL J message count (label 16)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_17(30417, "TADIL J message count (label 17)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_18(30418, "TADIL J message count (label 18)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_19(30419, "TADIL J message count (label 19)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_20(30420, "TADIL J message count (label 20)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_21(30421, "TADIL J message count (label 21)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_22(30422, "TADIL J message count (label 22)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_23(30423, "TADIL J message count (label 23)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_24(30424, "TADIL J message count (label 24)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_25(30425, "TADIL J message count (label 25)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_26(30426, "TADIL J message count (label 26)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_27(30427, "TADIL J message count (label 27)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_28(30428, "TADIL J message count (label 28)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_29(30429, "TADIL J message count (label 29)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_30(30430, "TADIL J message count (label 30)");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_MESSAGE_COUNT_LABEL_31(30431, "TADIL J message count (label 31)");
DatumSpecificationRecord DatumSpecificationRecord::POSITION(31000, "Position");
DatumSpecificationRecord DatumSpecificationRecord::ROUTE_WAYPOINT_TYPE(31010, "Route (Waypoint) type");
DatumSpecificationRecord DatumSpecificationRecord::MILGRID10(31100, "MilGrid10");
DatumSpecificationRecord DatumSpecificationRecord::GEOCENTRIC_COORDINATES(31200, "Geocentric Coordinates");
DatumSpecificationRecord DatumSpecificationRecord::X(31210, "X");
DatumSpecificationRecord DatumSpecificationRecord::Y(31220, "Y");
DatumSpecificationRecord DatumSpecificationRecord::Z(31230, "Z");
DatumSpecificationRecord DatumSpecificationRecord::LATITUDE(31300, "Latitude");
DatumSpecificationRecord DatumSpecificationRecord::LONGITUDE(31400, "Longitude");
DatumSpecificationRecord DatumSpecificationRecord::LINE_OF_SIGHT(31500, "Line of Sight");
DatumSpecificationRecord DatumSpecificationRecord::X_17(31510, "X");
DatumSpecificationRecord DatumSpecificationRecord::Y_18(31520, "Y");
DatumSpecificationRecord DatumSpecificationRecord::Z_19(31530, "Z");
DatumSpecificationRecord DatumSpecificationRecord::ALTITUDE(31600, "Altitude");
DatumSpecificationRecord DatumSpecificationRecord::DESTINATION_LATITUDE(31700, "Destination Latitude");
DatumSpecificationRecord DatumSpecificationRecord::DESTINATION_LONGITUDE(31800, "Destination Longitude");
DatumSpecificationRecord DatumSpecificationRecord::DESTINATION_ALTITUDE(31900, "Destination Altitude");
DatumSpecificationRecord DatumSpecificationRecord::ORIENTATION(32000, "Orientation");
DatumSpecificationRecord DatumSpecificationRecord::HULL_HEADING_ANGLE(32100, "Hull Heading Angle");
DatumSpecificationRecord DatumSpecificationRecord::HULL_PITCH_ANGLE(32200, "Hull Pitch Angle");
DatumSpecificationRecord DatumSpecificationRecord::ROLL_ANGLE(32300, "Roll Angle");
DatumSpecificationRecord DatumSpecificationRecord::X_20(32500, "X");
DatumSpecificationRecord DatumSpecificationRecord::Y_21(32600, "Y");
DatumSpecificationRecord DatumSpecificationRecord::Z_22(32700, "Z");
DatumSpecificationRecord DatumSpecificationRecord::APPEARANCE(33000, "Appearance");
DatumSpecificationRecord DatumSpecificationRecord::AMBIENT_LIGHTING(33100, "Ambient Lighting");
DatumSpecificationRecord DatumSpecificationRecord::LIGHTS(33101, "Lights");
DatumSpecificationRecord DatumSpecificationRecord::PAINT_SCHEME(33200, "Paint Scheme");
DatumSpecificationRecord DatumSpecificationRecord::SMOKE(33300, "Smoke");
DatumSpecificationRecord DatumSpecificationRecord::TRAILING_EFFECTS(33400, "Trailing Effects");
DatumSpecificationRecord DatumSpecificationRecord::FLAMING(33500, "Flaming");
DatumSpecificationRecord DatumSpecificationRecord::MARKING(33600, "Marking");
DatumSpecificationRecord DatumSpecificationRecord::MINE_PLOWS_ATTACHED(33710, "Mine Plows Attached");
DatumSpecificationRecord DatumSpecificationRecord::MINE_ROLLERS_ATTACHED(33720, "Mine Rollers Attached");
DatumSpecificationRecord DatumSpecificationRecord::TANK_TURRET_AZIMUTH(33730, "Tank Turret Azimuth");
DatumSpecificationRecord DatumSpecificationRecord::FAILURES_AND_MALFUNCTIONS(34000, "Failures and Malfunctions");
DatumSpecificationRecord DatumSpecificationRecord::AGE(34100, "Age");
DatumSpecificationRecord DatumSpecificationRecord::KILOMETERS(34110, "Kilometers");
DatumSpecificationRecord DatumSpecificationRecord::DAMAGE(35000, "Damage");
DatumSpecificationRecord DatumSpecificationRecord::CAUSE(35050, "Cause");
DatumSpecificationRecord DatumSpecificationRecord::MOBILITY_KILL(35100, "Mobility Kill");
DatumSpecificationRecord DatumSpecificationRecord::FIRE_POWER_KILL(35200, "Fire-Power Kill");
DatumSpecificationRecord DatumSpecificationRecord::PERSONNEL_CASUALTIES(35300, "Personnel Casualties");
DatumSpecificationRecord DatumSpecificationRecord::VELOCITY(36000, "Velocity");
DatumSpecificationRecord DatumSpecificationRecord::X_VELOCITY(36100, "X-velocity");
DatumSpecificationRecord DatumSpecificationRecord::Y_VELOCITY(36200, "Y-velocity");
DatumSpecificationRecord DatumSpecificationRecord::Z_VELOCITY(36300, "Z-velocity");
DatumSpecificationRecord DatumSpecificationRecord::SPEED(36400, "Speed");
DatumSpecificationRecord DatumSpecificationRecord::ACCELERATION(37000, "Acceleration");
DatumSpecificationRecord DatumSpecificationRecord::X_ACCELERATION(37100, "X-acceleration");
DatumSpecificationRecord DatumSpecificationRecord::Y_ACCELERATION(37200, "Y-acceleration");
DatumSpecificationRecord DatumSpecificationRecord::Z_ACCELERATION(37300, "Z-acceleration");
DatumSpecificationRecord DatumSpecificationRecord::ENGINE_STATUS(38100, "Engine Status");
DatumSpecificationRecord DatumSpecificationRecord::PRIMARY_TARGET_LINE_PTL(39000, "Primary Target Line (PTL)");
DatumSpecificationRecord DatumSpecificationRecord::EXERCISE(40000, "Exercise");
DatumSpecificationRecord DatumSpecificationRecord::EXERCISE_STATE(40010, "Exercise State");
DatumSpecificationRecord DatumSpecificationRecord::RESTART_REFRESH(40015, "Restart/Refresh");
DatumSpecificationRecord DatumSpecificationRecord::AFATDS_FILE_NAME(40020, "AFATDS File Name");
DatumSpecificationRecord DatumSpecificationRecord::TERRAIN_DATABASE(41000, "Terrain Database");
DatumSpecificationRecord DatumSpecificationRecord::X_41001(41001, "41001");
DatumSpecificationRecord DatumSpecificationRecord::MISSIONS(42000, "Missions");
DatumSpecificationRecord DatumSpecificationRecord::MISSION_ID(42100, "Mission ID");
DatumSpecificationRecord DatumSpecificationRecord::MISSION_TYPE(42200, "Mission Type");
DatumSpecificationRecord DatumSpecificationRecord::MISSION_REQUEST_TIME_STAMP(42300, "Mission Request Time Stamp");
DatumSpecificationRecord DatumSpecificationRecord::EXERCISE_DESCRIPTION(43000, "Exercise Description");
DatumSpecificationRecord DatumSpecificationRecord::NAME(43100, "Name");
DatumSpecificationRecord DatumSpecificationRecord::ENTITIES(43200, "Entities");
DatumSpecificationRecord DatumSpecificationRecord::VERSION(43300, "Version");
DatumSpecificationRecord DatumSpecificationRecord::GUISE_MODE(43410, "Guise Mode");
DatumSpecificationRecord DatumSpecificationRecord::SIMULATION_APPLICATION_ACTIVE_STATUS(43420, "Simulation Application Active Status");
DatumSpecificationRecord DatumSpecificationRecord::SIMULATION_APPLICATION_ROLE_RECORD(43430, "Simulation Application Role Record");
DatumSpecificationRecord DatumSpecificationRecord::SIMULATION_APPLICATION_STATE(43440, "Simulation Application State");
DatumSpecificationRecord DatumSpecificationRecord::VISUAL_OUTPUT_MODE(44000, "Visual Output Mode");
DatumSpecificationRecord DatumSpecificationRecord::SIMULATION_MANAGER_ROLE(44100, "Simulation Manager Role");
DatumSpecificationRecord DatumSpecificationRecord::SIMULATION_MANAGER_SITE_ID(44110, "Simulation Manager Site ID");
DatumSpecificationRecord DatumSpecificationRecord::SIMULATION_MANAGER_APPLIC_ID(44120, "Simulation Manager Applic. ID");
DatumSpecificationRecord DatumSpecificationRecord::SIMULATION_MANAGER_ENTITY_ID(44130, "Simulation Manager Entity ID");
DatumSpecificationRecord DatumSpecificationRecord::SIMULATION_MANAGER_ACTIVE_STATUS(44140, "Simulation Manager Active Status");
DatumSpecificationRecord DatumSpecificationRecord::AFTER_ACTIVE_REVIEW_ROLE(44200, "After Active Review Role");
DatumSpecificationRecord DatumSpecificationRecord::AFTER_ACTIVE_REVIEW_SITE_ID(44210, "After Active Review Site ID");
DatumSpecificationRecord DatumSpecificationRecord::AFTER_ACTIVE_APPLIC_ID(44220, "After Active Applic. ID");
DatumSpecificationRecord DatumSpecificationRecord::AFTER_ACTIVE_REVIEW_ENTITY_ID(44230, "After Active Review Entity ID");
DatumSpecificationRecord DatumSpecificationRecord::AFTER_ACTIVE_REVIEW_ACTIVE_STATUS(44240, "After Active Review Active Status");
DatumSpecificationRecord DatumSpecificationRecord::EXERCISE_LOGGER_ROLE(44300, "Exercise Logger Role");
DatumSpecificationRecord DatumSpecificationRecord::EXERCISE_LOGGER_SITE_ID(44310, "Exercise Logger Site ID");
DatumSpecificationRecord DatumSpecificationRecord::EXERCISE_LOGGER_APPLIC_ID(44320, "Exercise Logger Applic. ID");
DatumSpecificationRecord DatumSpecificationRecord::EXERCISE_ENTITY_ID(44330, "Exercise Entity ID");
DatumSpecificationRecord DatumSpecificationRecord::EXERCISE_LOGGER_ACTIVE_STATUS(44340, "Exercise Logger Active Status");
DatumSpecificationRecord DatumSpecificationRecord::SYNTHETIC_ENVIRONMENT_MANAGER_ROLE(44400, "Synthetic Environment Manager Role");
DatumSpecificationRecord DatumSpecificationRecord::SYNTHETIC_ENVIRONMENT_MANAGER_SITE_ID(44410, "Synthetic Environment Manager Site ID");
DatumSpecificationRecord DatumSpecificationRecord::SYNTHETIC_ENVIRONMENT_MANAGER_APPLIC_ID(44420, "Synthetic Environment Manager Applic. ID");
DatumSpecificationRecord DatumSpecificationRecord::SYNTHETIC_ENVIRONMENT_MANAGER_ENTITY_ID(44430, "Synthetic Environment Manager Entity ID");
DatumSpecificationRecord DatumSpecificationRecord::SYNTHETIC_ENVIRONMENT_MANAGER_ACTIVE_STATUS(44440, "Synthetic Environment Manager Active Status");
DatumSpecificationRecord DatumSpecificationRecord::SIMNET_DIS_TRANSLATOR_ROLE(44500, "SIMNET-DIS Translator Role");
DatumSpecificationRecord DatumSpecificationRecord::SIMNET_DIS_TRANSLATOR_SITE_ID(44510, "SIMNET-DIS Translator Site ID");
DatumSpecificationRecord DatumSpecificationRecord::SIMNET_DIS_TRANSLATOR_APPLIC_ID(44520, "SIMNET-DIS Translator Applic. ID");
DatumSpecificationRecord DatumSpecificationRecord::SIMNET_DIS_TRANSLATOR_ENTITY_ID(44530, "SIMNET-DIS Translator Entity ID");
DatumSpecificationRecord DatumSpecificationRecord::SIMNET_DIS_TRANSLATOR_ACTIVE_STATUS(44540, "SIMNET-DIS Translator Active Status");
DatumSpecificationRecord DatumSpecificationRecord::APPLICATION_RATE(45000, "Application Rate");
DatumSpecificationRecord DatumSpecificationRecord::APPLICATION_TIME(45005, "Application Time");
DatumSpecificationRecord DatumSpecificationRecord::APPLICATION_TIMESTEP(45010, "Application Timestep");
DatumSpecificationRecord DatumSpecificationRecord::FEEDBACK_TIME(45020, "Feedback Time");
DatumSpecificationRecord DatumSpecificationRecord::SIMULATION_RATE(45030, "Simulation Rate");
DatumSpecificationRecord DatumSpecificationRecord::SIMULATION_TIME(45040, "Simulation Time");
DatumSpecificationRecord DatumSpecificationRecord::SIMULATION_TIMESTEP(45050, "Simulation Timestep");
DatumSpecificationRecord DatumSpecificationRecord::TIME_INTERVAL(45060, "Time Interval");
DatumSpecificationRecord DatumSpecificationRecord::TIME_LATENCY(45070, "Time Latency");
DatumSpecificationRecord DatumSpecificationRecord::TIME_SCHEME(45080, "Time Scheme");
DatumSpecificationRecord DatumSpecificationRecord::EXERCISE_ELAPSED_TIME(46000, "Exercise Elapsed Time");
DatumSpecificationRecord DatumSpecificationRecord::ELAPSED_TIME(46010, "Elapsed Time");
DatumSpecificationRecord DatumSpecificationRecord::ENVIRONMENT(50000, "Environment");
DatumSpecificationRecord DatumSpecificationRecord::WEATHER(51000, "Weather");
DatumSpecificationRecord DatumSpecificationRecord::WEATHER_CONDITION(51010, "Weather Condition");
DatumSpecificationRecord DatumSpecificationRecord::THERMAL_CONDITION(51100, "Thermal Condition");
DatumSpecificationRecord DatumSpecificationRecord::THERMAL_VISIBILITY(51110, "Thermal Visibility");
DatumSpecificationRecord DatumSpecificationRecord::THERMAL_VISIBILITY_23(51111, "Thermal Visibility");
DatumSpecificationRecord DatumSpecificationRecord::TIME(52000, "Time");
DatumSpecificationRecord DatumSpecificationRecord::TIME_24(52001, "Time");
DatumSpecificationRecord DatumSpecificationRecord::TIME_OF_DAY_DISCRETE(52100, "Time of Day, Discrete");
DatumSpecificationRecord DatumSpecificationRecord::TIME_OF_DAY_CONTINUOUS(52200, "Time of Day, Continuous");
DatumSpecificationRecord DatumSpecificationRecord::TIME_MODE(52300, "Time Mode");
DatumSpecificationRecord DatumSpecificationRecord::TIME_SCENE(52305, "Time Scene");
DatumSpecificationRecord DatumSpecificationRecord::CURRENT_HOUR(52310, "Current Hour");
DatumSpecificationRecord DatumSpecificationRecord::CURRENT_MINUTE(52320, "Current Minute");
DatumSpecificationRecord DatumSpecificationRecord::CURRENT_SECOND(52330, "Current Second");
DatumSpecificationRecord DatumSpecificationRecord::AZIMUTH(52340, "Azimuth");
DatumSpecificationRecord DatumSpecificationRecord::MAXIMUM_ELEVATION(52350, "Maximum Elevation");
DatumSpecificationRecord DatumSpecificationRecord::TIME_ZONE(52360, "Time Zone");
DatumSpecificationRecord DatumSpecificationRecord::TIME_RATE(52370, "Time Rate");
DatumSpecificationRecord DatumSpecificationRecord::THE_NUMBER_OF_SIMULATION_SECONDS_SINCE_THE_START_OF_THE_EXERCISE_SIMULATION_TIME(52380, "The number of simulation seconds since the start of the exercise (simulation time)");
DatumSpecificationRecord DatumSpecificationRecord::TIME_SUNRISE_ENABLED(52400, "Time Sunrise Enabled");
DatumSpecificationRecord DatumSpecificationRecord::SUNRISE_HOUR(52410, "Sunrise Hour");
DatumSpecificationRecord DatumSpecificationRecord::SUNRISE_MINUTE(52420, "Sunrise Minute");
DatumSpecificationRecord DatumSpecificationRecord::SUNRISE_SECOND(52430, "Sunrise Second");
DatumSpecificationRecord DatumSpecificationRecord::SUNRISE_AZIMUTH(52440, "Sunrise Azimuth");
DatumSpecificationRecord DatumSpecificationRecord::TIME_SUNSET_ENABLED(52500, "Time Sunset Enabled");
DatumSpecificationRecord DatumSpecificationRecord::SUNSET_HOUR(52510, "Sunset Hour");
DatumSpecificationRecord DatumSpecificationRecord::SUNSET_HOUR_25(52511, "Sunset Hour");
DatumSpecificationRecord DatumSpecificationRecord::SUNSET_MINUTE(52520, "Sunset Minute");
DatumSpecificationRecord DatumSpecificationRecord::SUNSET_SECOND(52530, "Sunset Second");
DatumSpecificationRecord DatumSpecificationRecord::X_52531(52531, "52531");
DatumSpecificationRecord DatumSpecificationRecord::DATE(52600, "Date");
DatumSpecificationRecord DatumSpecificationRecord::DATE_EUROPEAN(52601, "Date (European)");
DatumSpecificationRecord DatumSpecificationRecord::DATE_US(52602, "Date (US)");
DatumSpecificationRecord DatumSpecificationRecord::MONTH(52610, "Month");
DatumSpecificationRecord DatumSpecificationRecord::DAY(52620, "Day");
DatumSpecificationRecord DatumSpecificationRecord::YEAR(52630, "Year");
DatumSpecificationRecord DatumSpecificationRecord::CLOUDS(53000, "Clouds");
DatumSpecificationRecord DatumSpecificationRecord::CLOUD_LAYER_ENABLE(53050, "Cloud Layer Enable");
DatumSpecificationRecord DatumSpecificationRecord::CLOUD_LAYER_SELECTION(53060, "Cloud Layer Selection");
DatumSpecificationRecord DatumSpecificationRecord::VISIBILITY(53100, "Visibility");
DatumSpecificationRecord DatumSpecificationRecord::BASE_ALTITUDE(53200, "Base Altitude");
DatumSpecificationRecord DatumSpecificationRecord::BASE_ALTITUDE_26(53250, "Base Altitude");
DatumSpecificationRecord DatumSpecificationRecord::CEILING(53300, "Ceiling");
DatumSpecificationRecord DatumSpecificationRecord::CEILING_27(53350, "Ceiling");
DatumSpecificationRecord DatumSpecificationRecord::CHARACTERISTICS(53400, "Characteristics");
DatumSpecificationRecord DatumSpecificationRecord::CONCENTRATION_LENGTH(53410, "Concentration Length");
DatumSpecificationRecord DatumSpecificationRecord::TRANSMITTANCE(53420, "Transmittance");
DatumSpecificationRecord DatumSpecificationRecord::RADIANCE(53430, "Radiance");
DatumSpecificationRecord DatumSpecificationRecord::PRECIPITATION(54000, "Precipitation");
DatumSpecificationRecord DatumSpecificationRecord::RAIN(54100, "Rain");
DatumSpecificationRecord DatumSpecificationRecord::FOG(55000, "Fog");
DatumSpecificationRecord DatumSpecificationRecord::VISIBILITY_28(55100, "Visibility");
DatumSpecificationRecord DatumSpecificationRecord::VISIBILITY_29(55101, "Visibility");
DatumSpecificationRecord DatumSpecificationRecord::VISIBILITY_30(55105, "Visibility");
DatumSpecificationRecord DatumSpecificationRecord::DENSITY(55200, "Density");
DatumSpecificationRecord DatumSpecificationRecord::BASE(55300, "Base");
DatumSpecificationRecord DatumSpecificationRecord::VIEW_LAYER_FROM_ABOVE(55401, "View Layer from above.");
DatumSpecificationRecord DatumSpecificationRecord::TRANSITION_RANGE(55410, "Transition Range");
DatumSpecificationRecord DatumSpecificationRecord::BOTTOM(55420, "Bottom");
DatumSpecificationRecord DatumSpecificationRecord::BOTTOM_31(55425, "Bottom");
DatumSpecificationRecord DatumSpecificationRecord::CEILING_32(55430, "Ceiling");
DatumSpecificationRecord DatumSpecificationRecord::CEILING_33(55435, "Ceiling");
DatumSpecificationRecord DatumSpecificationRecord::HEAVENLY_BODIES(56000, "Heavenly Bodies");
DatumSpecificationRecord DatumSpecificationRecord::SUN(56100, "Sun");
DatumSpecificationRecord DatumSpecificationRecord::SUN_VISIBLE(56105, "Sun Visible");
DatumSpecificationRecord DatumSpecificationRecord::POSITION_34(56110, "Position");
DatumSpecificationRecord DatumSpecificationRecord::SUN_POSITION_ELEVATION_DEGREES(56111, "Sun Position Elevation, Degrees");
DatumSpecificationRecord DatumSpecificationRecord::POSITION_AZIMUTH(56120, "Position Azimuth");
DatumSpecificationRecord DatumSpecificationRecord::SUN_POSITION_AZIMUTH_DEGREES(56121, "Sun Position Azimuth, Degrees");
DatumSpecificationRecord DatumSpecificationRecord::POSITION_ELEVATION(56130, "Position Elevation");
DatumSpecificationRecord DatumSpecificationRecord::POSITION_INTENSITY(56140, "Position Intensity");
DatumSpecificationRecord DatumSpecificationRecord::MOON(56200, "Moon");
DatumSpecificationRecord DatumSpecificationRecord::MOON_VISIBLE(56205, "Moon Visible");
DatumSpecificationRecord DatumSpecificationRecord::POSITION_35(56210, "Position");
DatumSpecificationRecord DatumSpecificationRecord::POSITION_AZIMUTH_36(56220, "Position Azimuth");
DatumSpecificationRecord DatumSpecificationRecord::MOON_POSITION_AZIMUTH_DEGREES(56221, "Moon Position Azimuth, Degrees");
DatumSpecificationRecord DatumSpecificationRecord::POSITION_ELEVATION_37(56230, "Position Elevation");
DatumSpecificationRecord DatumSpecificationRecord::MOON_POSITION_ELEVATION_DEGREES(56231, "Moon Position Elevation, Degrees");
DatumSpecificationRecord DatumSpecificationRecord::POSITION_INTENSITY_38(56240, "Position Intensity");
DatumSpecificationRecord DatumSpecificationRecord::HORIZON(56310, "Horizon");
DatumSpecificationRecord DatumSpecificationRecord::HORIZON_AZIMUTH(56320, "Horizon Azimuth");
DatumSpecificationRecord DatumSpecificationRecord::HORIZON_ELEVATION(56330, "Horizon Elevation");
DatumSpecificationRecord DatumSpecificationRecord::HORIZON_HEADING(56340, "Horizon Heading");
DatumSpecificationRecord DatumSpecificationRecord::HORIZON_INTENSITY(56350, "Horizon Intensity");
DatumSpecificationRecord DatumSpecificationRecord::HUMIDITY(57200, "Humidity");
DatumSpecificationRecord DatumSpecificationRecord::VISIBILITY_39(57300, "Visibility");
DatumSpecificationRecord DatumSpecificationRecord::WINDS(57400, "Winds");
DatumSpecificationRecord DatumSpecificationRecord::SPEED_40(57410, "Speed");
DatumSpecificationRecord DatumSpecificationRecord::WIND_SPEED_KNOTS(57411, "Wind Speed, Knots");
DatumSpecificationRecord DatumSpecificationRecord::WIND_DIRECTION(57420, "Wind Direction");
DatumSpecificationRecord DatumSpecificationRecord::WIND_DIRECTION_DEGREES(57421, "Wind Direction, Degrees");
DatumSpecificationRecord DatumSpecificationRecord::RAINSOAK(57500, "Rainsoak");
DatumSpecificationRecord DatumSpecificationRecord::TIDE_SPEED(57610, "Tide Speed");
DatumSpecificationRecord DatumSpecificationRecord::TIDE_SPEED_KNOTS(57611, "Tide Speed, Knots");
DatumSpecificationRecord DatumSpecificationRecord::TIDE_DIRECTION(57620, "Tide Direction");
DatumSpecificationRecord DatumSpecificationRecord::TIDE_DIRECTION_DEGREES(57621, "Tide Direction, Degrees");
DatumSpecificationRecord DatumSpecificationRecord::HAZE(58000, "Haze");
DatumSpecificationRecord DatumSpecificationRecord::VISIBILITY_41(58100, "Visibility");
DatumSpecificationRecord DatumSpecificationRecord::VISIBILITY_42(58105, "Visibility");
DatumSpecificationRecord DatumSpecificationRecord::DENSITY_43(58200, "Density");
DatumSpecificationRecord DatumSpecificationRecord::CEILING_44(58430, "Ceiling");
DatumSpecificationRecord DatumSpecificationRecord::CEILING_45(58435, "Ceiling");
DatumSpecificationRecord DatumSpecificationRecord::CONTAMINANTS_AND_OBSCURANTS(59000, "Contaminants and Obscurants");
DatumSpecificationRecord DatumSpecificationRecord::CONTAMINANT_OBSCURANT_TYPE(59100, "Contaminant/Obscurant Type");
DatumSpecificationRecord DatumSpecificationRecord::PERSISTENCE(59110, "Persistence");
DatumSpecificationRecord DatumSpecificationRecord::CHEMICAL_DOSAGE(59115, "Chemical Dosage");
DatumSpecificationRecord DatumSpecificationRecord::CHEMICAL_AIR_CONCENTRATION(59120, "Chemical Air Concentration");
DatumSpecificationRecord DatumSpecificationRecord::CHEMICAL_GROUND_DEPOSITION(59125, "Chemical Ground Deposition");
DatumSpecificationRecord DatumSpecificationRecord::CHEMICAL_MAXIMUM_GROUND_DEPOSITION(59130, "Chemical Maximum Ground Deposition");
DatumSpecificationRecord DatumSpecificationRecord::CHEMICAL_DOSAGE_THRESHOLD(59135, "Chemical Dosage Threshold");
DatumSpecificationRecord DatumSpecificationRecord::BIOLOGICAL_DOSAGE(59140, "Biological Dosage");
DatumSpecificationRecord DatumSpecificationRecord::BIOLOGICAL_AIR_CONCENTRATION(59145, "Biological Air Concentration");
DatumSpecificationRecord DatumSpecificationRecord::BIOLOGICAL_DOSAGE_THRESHOLD(59150, "Biological Dosage Threshold");
DatumSpecificationRecord DatumSpecificationRecord::BIOLOGICAL_BINNED_PARTICLE_COUNT(59155, "Biological Binned Particle Count");
DatumSpecificationRecord DatumSpecificationRecord::RADIOLOGICAL_DOSAGE(59160, "Radiological Dosage");
DatumSpecificationRecord DatumSpecificationRecord::COMMUNICATIONS(60000, "Communications");
DatumSpecificationRecord DatumSpecificationRecord::CHANNEL_TYPE(61100, "Channel Type");
DatumSpecificationRecord DatumSpecificationRecord::CHANNEL_TYPE_46(61101, "Channel Type");
DatumSpecificationRecord DatumSpecificationRecord::CHANNEL_IDENTIFICATION(61200, "Channel Identification");
DatumSpecificationRecord DatumSpecificationRecord::ALPHA_IDENTIFICATION(61300, "Alpha Identification");
DatumSpecificationRecord DatumSpecificationRecord::X_61301(61301, "61301");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_IDENTIFICATION(61400, "Radio Identification");
DatumSpecificationRecord DatumSpecificationRecord::X_61401(61401, "61401");
DatumSpecificationRecord DatumSpecificationRecord::LAND_LINE_IDENTIFICATION(61500, "Land Line Identification");
DatumSpecificationRecord DatumSpecificationRecord::INTERCOM_IDENTIFICATION(61600, "Intercom Identification");
DatumSpecificationRecord DatumSpecificationRecord::GROUP_NETWORK_CHANNEL_NUMBER(61700, "Group Network Channel Number");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_COMMUNICATIONS_STATUS(62100, "Radio Communications Status");
DatumSpecificationRecord DatumSpecificationRecord::STATIONARY_RADIO_TRANSMITTERS_DEFAULT_TIME(62200, "Stationary Radio Transmitters Default Time");
DatumSpecificationRecord DatumSpecificationRecord::MOVING_RADIO_TRANSMITTERS_DEFAULT_TIME(62300, "Moving Radio Transmitters Default Time");
DatumSpecificationRecord DatumSpecificationRecord::STATIONARY_RADIO_SIGNALS_DEFAULT_TIME(62400, "Stationary Radio Signals Default Time");
DatumSpecificationRecord DatumSpecificationRecord::MOVING_RADIO_SIGNAL_DEFAULT_TIME(62500, "Moving Radio Signal Default Time");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_INITIALIZATION_TRANSEC_SECURITY_KEY(63101, "Radio Initialization Transec Security Key");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_INITIALIZATION_INTERNAL_NOISE_LEVEL(63102, "Radio Initialization Internal Noise Level");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_INITIALIZATION_SQUELCH_THRESHOLD(63103, "Radio Initialization Squelch Threshold");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_INITIALIZATION_ANTENNA_LOCATION(63104, "Radio Initialization Antenna Location");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_INITIALIZATION_ANTENNA_PATTERN_TYPE(63105, "Radio Initialization Antenna Pattern Type");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_INITIALIZATION_ANTENNA_PATTERN_LENGTH(63106, "Radio Initialization Antenna Pattern Length");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_INITIALIZATION_BEAM_DEFINITION(63107, "Radio Initialization Beam Definition");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_INITIALIZATION_TRANSMIT_HEARTBEAT_TIME(63108, "Radio Initialization Transmit Heartbeat Time");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_INITIALIZATION_TRANSMIT_DISTANCE_THRESHOLD_VARIABLE_RECORD(63109, "Radio Initialization Transmit Distance Threshold Variable Record");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_CHANNEL_INITIALIZATION_LOCKOUT_ID(63110, "Radio Channel Initialization Lockout ID");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_CHANNEL_INITIALIZATION_HOPSET_ID(63111, "Radio Channel Initialization Hopset ID");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_CHANNEL_INITIALIZATION_PRESET_FREQUENCY(63112, "Radio Channel Initialization Preset Frequency");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_CHANNEL_INITIALIZATION_FREQUENCY_SYNC_TIME(63113, "Radio Channel Initialization Frequency Sync Time");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_CHANNEL_INITIALIZATION_COMSEC_KEY(63114, "Radio Channel Initialization Comsec Key");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_CHANNEL_INITIALIZATION_ALPHA(63115, "Radio Channel Initialization Alpha");
DatumSpecificationRecord DatumSpecificationRecord::ALGORITHM_PARAMETERS(70000, "Algorithm Parameters");
DatumSpecificationRecord DatumSpecificationRecord::DEAD_RECKONING_ALGORITHM_DRA(71000, "Dead Reckoning Algorithm (DRA)");
DatumSpecificationRecord DatumSpecificationRecord::DRA_LOCATION_THRESHOLD(71100, "DRA Location Threshold");
DatumSpecificationRecord DatumSpecificationRecord::DRA_ORIENTATION_THRESHOLD(71200, "DRA Orientation Threshold");
DatumSpecificationRecord DatumSpecificationRecord::DRA_TIME_THRESHOLD(71300, "DRA Time Threshold");
DatumSpecificationRecord DatumSpecificationRecord::SIMULATION_MANAGEMENT_PARAMETERS(72000, "Simulation Management Parameters");
DatumSpecificationRecord DatumSpecificationRecord::CHECKPOINT_INTERVAL(72100, "Checkpoint Interval");
DatumSpecificationRecord DatumSpecificationRecord::TRANSMITTER_TIME_THRESHOLD(72600, "Transmitter Time Threshold");
DatumSpecificationRecord DatumSpecificationRecord::RECEIVER_TIME_THRESHOLD(72700, "Receiver Time Threshold");
DatumSpecificationRecord DatumSpecificationRecord::INTEROPERABILITY_MODE(73000, "Interoperability Mode");
DatumSpecificationRecord DatumSpecificationRecord::SIMNET_DATA_COLLECTION(74000, "SIMNET Data Collection");
DatumSpecificationRecord DatumSpecificationRecord::EVENT_ID(75000, "Event ID");
DatumSpecificationRecord DatumSpecificationRecord::SOURCE_SITE_ID(75100, "Source Site ID");
DatumSpecificationRecord DatumSpecificationRecord::SOURCE_HOST_ID(75200, "Source Host ID");
DatumSpecificationRecord DatumSpecificationRecord::ARTICULATED_PARTS(90000, "Articulated Parts");
DatumSpecificationRecord DatumSpecificationRecord::X_90001(90001, "90001");
DatumSpecificationRecord DatumSpecificationRecord::PART_ID(90050, "Part ID");
DatumSpecificationRecord DatumSpecificationRecord::INDEX(90070, "Index");
DatumSpecificationRecord DatumSpecificationRecord::POSITION_47(90100, "Position");
DatumSpecificationRecord DatumSpecificationRecord::POSITION_RATE(90200, "Position Rate");
DatumSpecificationRecord DatumSpecificationRecord::EXTENSION(90300, "Extension");
DatumSpecificationRecord DatumSpecificationRecord::EXTENSION_RATE(90400, "Extension Rate");
DatumSpecificationRecord DatumSpecificationRecord::X_48(90500, "X");
DatumSpecificationRecord DatumSpecificationRecord::X_RATE(90600, "X-rate");
DatumSpecificationRecord DatumSpecificationRecord::Y_49(90700, "Y");
DatumSpecificationRecord DatumSpecificationRecord::Y_RATE(90800, "Y-rate");
DatumSpecificationRecord DatumSpecificationRecord::Z_50(90900, "Z");
DatumSpecificationRecord DatumSpecificationRecord::Z_RATE(91000, "Z-rate");
DatumSpecificationRecord DatumSpecificationRecord::AZIMUTH_51(91100, "Azimuth");
DatumSpecificationRecord DatumSpecificationRecord::AZIMUTH_RATE(91200, "Azimuth Rate");
DatumSpecificationRecord DatumSpecificationRecord::ELEVATION(91300, "Elevation");
DatumSpecificationRecord DatumSpecificationRecord::ELEVATION_RATE(91400, "Elevation Rate");
DatumSpecificationRecord DatumSpecificationRecord::ROTATION(91500, "Rotation");
DatumSpecificationRecord DatumSpecificationRecord::ROTATION_RATE(91600, "Rotation Rate");
DatumSpecificationRecord DatumSpecificationRecord::DRA_ANGULAR_X_VELOCITY(100001, "DRA Angular X-Velocity");
DatumSpecificationRecord DatumSpecificationRecord::DRA_ANGULAR_Y_VELOCITY(100002, "DRA Angular Y-Velocity");
DatumSpecificationRecord DatumSpecificationRecord::DRA_ANGULAR_Z_VELOCITY(100003, "DRA Angular Z-Velocity");
DatumSpecificationRecord DatumSpecificationRecord::APPEARANCE_TRAILING_EFFECTS(100004, "Appearance, Trailing Effects");
DatumSpecificationRecord DatumSpecificationRecord::APPEARANCE_HATCH(100005, "Appearance, Hatch");
DatumSpecificationRecord DatumSpecificationRecord::APPEARANCE_CHARACTER_SET(100008, "Appearance, Character Set");
DatumSpecificationRecord DatumSpecificationRecord::CAPABILITY_AMMUNITION_SUPPLIER(100010, "Capability, Ammunition Supplier");
DatumSpecificationRecord DatumSpecificationRecord::CAPABILITY_MISCELLANEOUS_SUPPLIER(100011, "Capability, Miscellaneous Supplier");
DatumSpecificationRecord DatumSpecificationRecord::CAPABILITY_REPAIR_PROVIDER(100012, "Capability, Repair Provider");
DatumSpecificationRecord DatumSpecificationRecord::ARTICULATION_PARAMETER(100014, "Articulation Parameter");
DatumSpecificationRecord DatumSpecificationRecord::ARTICULATION_PARAMETER_TYPE(100047, "Articulation Parameter Type");
DatumSpecificationRecord DatumSpecificationRecord::ARTICULATION_PARAMETER_VALUE(100048, "Articulation Parameter Value");
DatumSpecificationRecord DatumSpecificationRecord::TIME_OF_DAY_SCENE(100058, "Time of Day-Scene");
DatumSpecificationRecord DatumSpecificationRecord::LATITUDE_NORTH_LOCATION_OF_WEATHER_CELL(100061, "Latitude-North (Location of weather cell)");
DatumSpecificationRecord DatumSpecificationRecord::LONGITUDE_EAST_LOCATION_OF_WEATHER_CELL(100063, "Longitude-East (Location of weather cell)");
DatumSpecificationRecord DatumSpecificationRecord::TACTICAL_DRIVER_STATUS(100068, "Tactical Driver Status");
DatumSpecificationRecord DatumSpecificationRecord::SONAR_SYSTEM_STATUS(100100, "Sonar System Status");
DatumSpecificationRecord DatumSpecificationRecord::UPPER_LATITUDE(100161, "Upper latitude");
DatumSpecificationRecord DatumSpecificationRecord::LATITUDE_SOUTH_LOCATION_OF_WEATHER_CELL(100162, "Latitude-South (Location of weather cell)");
DatumSpecificationRecord DatumSpecificationRecord::WESTERN_LONGITUDE(100163, "Western longitude");
DatumSpecificationRecord DatumSpecificationRecord::LONGITUDE_WEST_LOCATION_OF_WEATHER_CELL(100164, "Longitude-West (location of weather cell)");
DatumSpecificationRecord DatumSpecificationRecord::ACCOMPLISHED_ACCEPT(100165, "Accomplished accept");
DatumSpecificationRecord DatumSpecificationRecord::CD_ROM_NUMBER_DISK_ID_FOR_TERRAIN(100165, "CD ROM Number (Disk ID for terrain)");
DatumSpecificationRecord DatumSpecificationRecord::DTED_DISK_ID(100166, "DTED disk ID");
DatumSpecificationRecord DatumSpecificationRecord::ALTITUDE_52(100167, "Altitude");
DatumSpecificationRecord DatumSpecificationRecord::TACTICAL_SYSTEM_STATUS(100169, "Tactical System Status");
DatumSpecificationRecord DatumSpecificationRecord::JTIDS_STATUS(100170, "JTIDS Status");
DatumSpecificationRecord DatumSpecificationRecord::TADIL_J_STATUS(100171, "TADIL-J Status");
DatumSpecificationRecord DatumSpecificationRecord::DSDD_STATUS(100172, "DSDD Status");
DatumSpecificationRecord DatumSpecificationRecord::WEAPON_SYSTEM_STATUS(100200, "Weapon System Status");
DatumSpecificationRecord DatumSpecificationRecord::SUBSYSTEM_STATUS(100205, "Subsystem status");
DatumSpecificationRecord DatumSpecificationRecord::NUMBER_OF_INTERCEPTORS_FIRED(100206, "Number of interceptors fired");
DatumSpecificationRecord DatumSpecificationRecord::NUMBER_OF_INTERCEPTOR_DETONATIONS(100207, "Number of interceptor detonations");
DatumSpecificationRecord DatumSpecificationRecord::NUMBER_OF_MESSAGE_BUFFERS_DROPPED(100208, "Number of message buffers dropped");
DatumSpecificationRecord DatumSpecificationRecord::SATELLITE_SENSOR_BACKGROUND_YEAR_DAY(100213, "Satellite sensor background (year, day)");
DatumSpecificationRecord DatumSpecificationRecord::SATELLITE_SENSOR_BACKGROUND_HOUR_MINUTE(100214, "Satellite sensor background (hour, minute)");
DatumSpecificationRecord DatumSpecificationRecord::SCRIPT_NUMBER(100218, "Script Number");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_TRACK_UPDATE_DATA(100300, "Entity/Track/Update Data");
DatumSpecificationRecord DatumSpecificationRecord::LOCAL_FORCE_TRAINING(100400, "Local/Force Training");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_TRACK_IDENTITY_DATA(100500, "Entity/Track Identity Data");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_FOR_TRACK_EVENT(100510, "Entity for Track Event");
DatumSpecificationRecord DatumSpecificationRecord::IFF_FRIEND_FOE_STATUS(100520, "IFF (Friend-Foe) status");
DatumSpecificationRecord DatumSpecificationRecord::ENGAGEMENT_DATA(100600, "Engagement Data");
DatumSpecificationRecord DatumSpecificationRecord::TARGET_LATITUDE(100610, "Target Latitude");
DatumSpecificationRecord DatumSpecificationRecord::TARGET_LONGITUDE(100620, "Target Longitude");
DatumSpecificationRecord DatumSpecificationRecord::AREA_OF_INTEREST_GROUND_IMPACT_CIRCLE_CENTER_LATITUDE(100631, "Area of Interest (Ground Impact Circle) Center Latitude");
DatumSpecificationRecord DatumSpecificationRecord::AREA_OF_INTEREST_GROUND_IMPACT_CIRCLE_CENTER_LONGITUDE(100632, "Area of Interest (Ground Impact Circle) Center Longitude");
DatumSpecificationRecord DatumSpecificationRecord::AREA_OF_INTEREST_GROUND_IMPACT_CIRCLE_RADIUS(100633, "Area of Interest (Ground Impact Circle) Radius");
DatumSpecificationRecord DatumSpecificationRecord::AREA_OF_INTEREST_TYPE(100634, "Area of Interest Type");
DatumSpecificationRecord DatumSpecificationRecord::TARGET_AGGREGATE_ID(100640, "Target Aggregate ID");
DatumSpecificationRecord DatumSpecificationRecord::GIC_IDENTIFICATION_NUMBER(100650, "GIC Identification Number");
DatumSpecificationRecord DatumSpecificationRecord::ESTIMATED_TIME_OF_FLIGHT_TO_TBM_IMPACT(100660, "Estimated Time of Flight to TBM Impact");
DatumSpecificationRecord DatumSpecificationRecord::ESTIMATED_INTERCEPT_TIME(100661, "Estimated Intercept Time");
DatumSpecificationRecord DatumSpecificationRecord::ESTIMATED_TIME_OF_FLIGHT_TO_NEXT_WAYPOINT(100662, "Estimated Time of Flight to Next Waypoint");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_TRACK_EQUIPMENT_DATA(100700, "Entity/Track Equipment Data");
DatumSpecificationRecord DatumSpecificationRecord::EMISSION_EW_DATA(100800, "Emission/EW Data");
DatumSpecificationRecord DatumSpecificationRecord::APPEARANCE_DATA(100900, "Appearance Data");
DatumSpecificationRecord DatumSpecificationRecord::COMMAND_ORDER_DATA(101000, "Command/Order Data");
DatumSpecificationRecord DatumSpecificationRecord::ENVIRONMENTAL_DATA(101100, "Environmental Data");
DatumSpecificationRecord DatumSpecificationRecord::SIGNIFICANT_EVENT_DATA(101200, "Significant Event Data");
DatumSpecificationRecord DatumSpecificationRecord::OPERATOR_ACTION_DATA(101300, "Operator Action Data");
DatumSpecificationRecord DatumSpecificationRecord::ADA_ENGAGEMENT_MODE(101310, "ADA Engagement Mode");
DatumSpecificationRecord DatumSpecificationRecord::ADA_SHOOTING_STATUS(101320, "ADA Shooting Status");
DatumSpecificationRecord DatumSpecificationRecord::ADA_MODE(101321, "ADA Mode");
DatumSpecificationRecord DatumSpecificationRecord::ADA_RADAR_STATUS(101330, "ADA Radar Status");
DatumSpecificationRecord DatumSpecificationRecord::SHOOT_COMMAND(101340, "Shoot Command");
DatumSpecificationRecord DatumSpecificationRecord::ADA_WEAPON_STATUS(101350, "ADA Weapon Status");
DatumSpecificationRecord DatumSpecificationRecord::ADA_FIRING_DISCIPLE(101360, "ADA Firing Disciple");
DatumSpecificationRecord DatumSpecificationRecord::ORDER_STATUS(101370, "Order Status");
DatumSpecificationRecord DatumSpecificationRecord::TIME_SYNCHRONIZATION(101400, "Time Synchronization");
DatumSpecificationRecord DatumSpecificationRecord::TOMAHAWK_DATA(101500, "Tomahawk Data");
DatumSpecificationRecord DatumSpecificationRecord::NUMBER_OF_DETONATIONS(102100, "Number of Detonations");
DatumSpecificationRecord DatumSpecificationRecord::NUMBER_OF_INTERCEPTS(102200, "Number of Intercepts");
DatumSpecificationRecord DatumSpecificationRecord::OBT_CONTROL_MT_201(200201, "OBT Control MT-201");
DatumSpecificationRecord DatumSpecificationRecord::SENSOR_DATA_MT_202(200202, "Sensor Data MT-202");
DatumSpecificationRecord DatumSpecificationRecord::ENVIRONMENTAL_DATA_MT_203(200203, "Environmental Data MT-203");
DatumSpecificationRecord DatumSpecificationRecord::OWNSHIP_DATA_MT_204(200204, "Ownship Data MT-204");
DatumSpecificationRecord DatumSpecificationRecord::ACOUSTIC_CONTACT_DATA_MT_205(200205, "Acoustic Contact Data MT-205");
DatumSpecificationRecord DatumSpecificationRecord::SONOBUOY_DATA_MT_207(200207, "Sonobuoy Data MT-207");
DatumSpecificationRecord DatumSpecificationRecord::SONOBUOY_CONTACT_DATA_MT_210(200210, "Sonobuoy Contact Data MT-210");
DatumSpecificationRecord DatumSpecificationRecord::HELO_CONTROL_MT_211(200211, "Helo Control MT-211");
DatumSpecificationRecord DatumSpecificationRecord::ESM_CONTROL_DATA(200213, "ESM Control Data");
DatumSpecificationRecord DatumSpecificationRecord::ESM_CONTACT_DATA_MT_214(200214, "ESM Contact Data MT-214");
DatumSpecificationRecord DatumSpecificationRecord::ESM_EMITTER_DATA_MT_215(200215, "ESM Emitter Data MT-215");
DatumSpecificationRecord DatumSpecificationRecord::WEAPON_DEFINITION_DATA_MT_217(200216, "Weapon Definition Data MT-217");
DatumSpecificationRecord DatumSpecificationRecord::WEAPON_PRESET_DATA_MT_217(200217, "Weapon Preset Data MT-217");
DatumSpecificationRecord DatumSpecificationRecord::OBT_CONTROL_MT_301(200301, "OBT Control MT-301");
DatumSpecificationRecord DatumSpecificationRecord::SENSOR_DATA_MT_302(200302, "Sensor Data MT-302");
DatumSpecificationRecord DatumSpecificationRecord::ENVIRONMENTAL_DATA_MT_303M(200303, "Environmental Data MT-303m");
DatumSpecificationRecord DatumSpecificationRecord::OWNSHIP_DATA_MT_304(200304, "Ownship Data MT-304");
DatumSpecificationRecord DatumSpecificationRecord::ACOUSTIC_CONTACT_DATA_MT_305(200305, "Acoustic Contact Data MT-305");
DatumSpecificationRecord DatumSpecificationRecord::SONOBUOY_DATA_MT_307(200307, "Sonobuoy Data MT-307");
DatumSpecificationRecord DatumSpecificationRecord::SONOBUOY_CONTACT_DATA_MT_310(200310, "Sonobuoy Contact Data MT-310");
DatumSpecificationRecord DatumSpecificationRecord::HELO_SCENARIO_EQUIPMENT_STATUS(200311, "Helo Scenario / Equipment Status");
DatumSpecificationRecord DatumSpecificationRecord::ESM_CONTROL_DATA_MT_313(200313, "ESM Control Data MT-313");
DatumSpecificationRecord DatumSpecificationRecord::ESM_CONTACT_DATA_MT_314(200314, "ESM Contact Data MT-314");
DatumSpecificationRecord DatumSpecificationRecord::ESM_EMITTER_DATA_MT_315(200315, "ESM Emitter Data MT-315");
DatumSpecificationRecord DatumSpecificationRecord::WEAPON_DEFINITION_DATA_MT_316(200316, "Weapon Definition Data MT-316");
DatumSpecificationRecord DatumSpecificationRecord::WEAPON_PRESET_DATA_MT_317(200317, "Weapon Preset Data MT-317");
DatumSpecificationRecord DatumSpecificationRecord::PAIRING_ASSOCIATION_EMT_56(200400, "Pairing/Association (eMT-56)");
DatumSpecificationRecord DatumSpecificationRecord::POINTER_EMT_57(200401, "Pointer (eMT-57)");
DatumSpecificationRecord DatumSpecificationRecord::REPORTING_RESPONSIBILITY_EMT_58(200402, "Reporting Responsibility (eMT-58)");
DatumSpecificationRecord DatumSpecificationRecord::TRACK_NUMBER_EMT_59(200403, "Track Number (eMT-59)");
DatumSpecificationRecord DatumSpecificationRecord::ID_FOR_LINK_11_REPORTING_EMT_60(200404, "ID for Link-11 Reporting (eMT-60)");
DatumSpecificationRecord DatumSpecificationRecord::REMOTE_TRACK_EMT_62(200405, "Remote Track (eMT-62)");
DatumSpecificationRecord DatumSpecificationRecord::LINK_11_ERROR_RATE_EMT_63(200406, "Link-11 Error Rate (eMT-63)");
DatumSpecificationRecord DatumSpecificationRecord::TRACK_QUALITY_EMT_64(200407, "Track Quality (eMT-64)");
DatumSpecificationRecord DatumSpecificationRecord::GRIDLOCK_EMT_65(200408, "Gridlock (eMT-65)");
DatumSpecificationRecord DatumSpecificationRecord::KILL_EMT_66(200409, "Kill (eMT-66)");
DatumSpecificationRecord DatumSpecificationRecord::TRACK_ID_CHANGE_RESOLUTION_EMT_68(200410, "Track ID Change / Resolution (eMT-68)");
DatumSpecificationRecord DatumSpecificationRecord::WEAPONS_STATUS_EMT_69(200411, "Weapons Status (eMT-69)");
DatumSpecificationRecord DatumSpecificationRecord::LINK_11_OPERATOR_EMT_70(200412, "Link-11 Operator (eMT-70)");
DatumSpecificationRecord DatumSpecificationRecord::FORCE_TRAINING_TRANSMIT_EMT_71(200413, "Force Training Transmit (eMT-71)");
DatumSpecificationRecord DatumSpecificationRecord::FORCE_TRAINING_RECEIVE_EMT_72(200414, "Force Training Receive (eMT-72)");
DatumSpecificationRecord DatumSpecificationRecord::INTERCEPTOR_AMPLIFICATION_EMT_75(200415, "Interceptor Amplification (eMT-75)");
DatumSpecificationRecord DatumSpecificationRecord::CONSUMABLES_EMT_78(200416, "Consumables (eMT-78)");
DatumSpecificationRecord DatumSpecificationRecord::LINK_11_LOCAL_TRACK_QUALITY_EMT_95(200417, "Link-11 Local Track Quality (eMT-95)");
DatumSpecificationRecord DatumSpecificationRecord::DLRP_EMT_19(200418, "DLRP (eMT-19)");
DatumSpecificationRecord DatumSpecificationRecord::FORCE_ORDER_EMT_52(200419, "Force Order (eMT-52)");
DatumSpecificationRecord DatumSpecificationRecord::WILCO_CANTCO_EMT_53(200420, "Wilco / Cantco (eMT-53)");
DatumSpecificationRecord DatumSpecificationRecord::EMC_BEARING_EMT_54(200421, "EMC Bearing (eMT-54)");
DatumSpecificationRecord DatumSpecificationRecord::CHANGE_TRACK_ELIGIBILITY_EMT_55(200422, "Change Track Eligibility (eMT-55)");
DatumSpecificationRecord DatumSpecificationRecord::LAND_MASS_REFERENCE_POINT(200423, "Land Mass Reference Point");
DatumSpecificationRecord DatumSpecificationRecord::SYSTEM_REFERENCE_POINT(200424, "System Reference Point");
DatumSpecificationRecord DatumSpecificationRecord::PU_AMPLIFICATION(200425, "PU Amplification");
DatumSpecificationRecord DatumSpecificationRecord::SET_DRIFT(200426, "Set/Drift");
DatumSpecificationRecord DatumSpecificationRecord::BEGIN_INITIALIZATION_MT_1(200427, "Begin Initialization (MT-1)");
DatumSpecificationRecord DatumSpecificationRecord::STATUS_AND_CONTROL_MT_3(200428, "Status and Control (MT-3)");
DatumSpecificationRecord DatumSpecificationRecord::SCINTILLATION_CHANGE_MT_39(200429, "Scintillation Change (MT-39)");
DatumSpecificationRecord DatumSpecificationRecord::LINK_11_ID_CONTROL_MT_61(200430, "Link 11 ID Control (MT-61)");
DatumSpecificationRecord DatumSpecificationRecord::PU_GUARD_LIST(200431, "PU Guard List");
DatumSpecificationRecord DatumSpecificationRecord::WINDS_ALOFT_MT_14(200432, "Winds Aloft (MT-14)");
DatumSpecificationRecord DatumSpecificationRecord::SURFACE_WINDS_MT_15(200433, "Surface Winds (MT-15)");
DatumSpecificationRecord DatumSpecificationRecord::SEA_STATE_MT_17(200434, "Sea State (MT-17)");
DatumSpecificationRecord DatumSpecificationRecord::MAGNETIC_VARIATION_MT_37(200435, "Magnetic Variation (MT-37)");
DatumSpecificationRecord DatumSpecificationRecord::TRACK_ELIGIBILITY_MT_29(200436, "Track Eligibility (MT-29)");
DatumSpecificationRecord DatumSpecificationRecord::TRAINING_TRACK_NOTIFICATION(200437, "Training Track Notification");
DatumSpecificationRecord DatumSpecificationRecord::TACAN_DATA_MT_32(200501, "Tacan Data (MT-32)");
DatumSpecificationRecord DatumSpecificationRecord::INTERCEPTOR_AMPLIFICATION_MT_75(200502, "Interceptor Amplification (MT-75)");
DatumSpecificationRecord DatumSpecificationRecord::TACAN_ASSIGNMENT_MT_76(200503, "Tacan Assignment (MT-76)");
DatumSpecificationRecord DatumSpecificationRecord::AUTOPILOT_STATUS_MT_77(200504, "Autopilot Status (MT-77)");
DatumSpecificationRecord DatumSpecificationRecord::CONSUMABLES_MT_78(200505, "Consumables (MT-78)");
DatumSpecificationRecord DatumSpecificationRecord::DOWNLINK_MT_79(200506, "Downlink (MT-79)");
DatumSpecificationRecord DatumSpecificationRecord::TIN_REPORT_MT_80(200507, "TIN Report (MT-80)");
DatumSpecificationRecord DatumSpecificationRecord::SPECIAL_POINT_CONTROL_MT_81(200508, "Special Point Control (MT-81)");
DatumSpecificationRecord DatumSpecificationRecord::CONTROL_DISCRETES_MT_82(200509, "Control Discretes (MT-82)");
DatumSpecificationRecord DatumSpecificationRecord::REQUEST_TARGET_DISCRETESMT_83(200510, "Request Target Discretes(MT-83)");
DatumSpecificationRecord DatumSpecificationRecord::TARGET_DISCRETES_MT_84(200511, "Target Discretes (MT-84)");
DatumSpecificationRecord DatumSpecificationRecord::REPLY_DISCRETES_MT_85(200512, "Reply Discretes (MT-85)");
DatumSpecificationRecord DatumSpecificationRecord::COMMAND_MANEUVERS_MT_86(200513, "Command Maneuvers (MT-86)");
DatumSpecificationRecord DatumSpecificationRecord::TARGET_DATA_MT_87(200514, "Target Data (MT-87)");
DatumSpecificationRecord DatumSpecificationRecord::TARGET_POINTER_MT_88(200515, "Target Pointer (MT-88)");
DatumSpecificationRecord DatumSpecificationRecord::INTERCEPT_DATA_MT_89(200516, "Intercept Data (MT-89)");
DatumSpecificationRecord DatumSpecificationRecord::DECREMENT_MISSILE_INVENTORY_MT_90(200517, "Decrement Missile Inventory (MT-90)");
DatumSpecificationRecord DatumSpecificationRecord::LINK_4A_ALERT_MT_91(200518, "Link-4A Alert (MT-91)");
DatumSpecificationRecord DatumSpecificationRecord::STRIKE_CONTROL_MT_92(200519, "Strike Control (MT-92)");
DatumSpecificationRecord DatumSpecificationRecord::SPEED_CHANGE_MT_25(200521, "Speed Change (MT-25)");
DatumSpecificationRecord DatumSpecificationRecord::COURSE_CHANGE_MT_26(200522, "Course Change (MT-26)");
DatumSpecificationRecord DatumSpecificationRecord::ALTITUDE_CHANGE_MT_27(200523, "Altitude Change (MT-27)");
DatumSpecificationRecord DatumSpecificationRecord::ACLS_AN_SPN_46_STATUS(200524, "ACLS AN/SPN-46 Status");
DatumSpecificationRecord DatumSpecificationRecord::ACLS_AIRCRAFT_REPORT(200525, "ACLS Aircraft Report");
DatumSpecificationRecord DatumSpecificationRecord::SPS_67_RADAR_OPERATOR_FUNCTIONS(200600, "SPS-67 Radar Operator Functions");
DatumSpecificationRecord DatumSpecificationRecord::SPS_55_RADAR_OPERATOR_FUNCTIONS(200601, "SPS-55 Radar Operator Functions");
DatumSpecificationRecord DatumSpecificationRecord::SPQ_9A_RADAR_OPERATOR_FUNCTIONS(200602, "SPQ-9A Radar Operator Functions");
DatumSpecificationRecord DatumSpecificationRecord::SPS_49_RADAR_OPERATOR_FUNCTIONS(200603, "SPS-49 Radar Operator Functions");
DatumSpecificationRecord DatumSpecificationRecord::MK_23_RADAR_OPERATOR_FUNCTIONS(200604, "MK-23 Radar Operator Functions");
DatumSpecificationRecord DatumSpecificationRecord::SPS_48_RADAR_OPERATOR_FUNCTIONS(200605, "SPS-48 Radar Operator Functions");
DatumSpecificationRecord DatumSpecificationRecord::SPS_40_RADAR_OPERATOR_FUNCTIONS(200606, "SPS-40 Radar Operator Functions");
DatumSpecificationRecord DatumSpecificationRecord::MK_95_RADAR_OPERATOR_FUNCTIONS(200607, "MK-95 Radar Operator Functions");
DatumSpecificationRecord DatumSpecificationRecord::KILL_NO_KILL(200608, "Kill/No Kill");
DatumSpecificationRecord DatumSpecificationRecord::CMT_PC(200609, "CMT pc");
DatumSpecificationRecord DatumSpecificationRecord::CMC4AIRGLOBALDATA(200610, "CMC4AirGlobalData");
DatumSpecificationRecord DatumSpecificationRecord::CMC4GLOBALDATA(200611, "CMC4GlobalData");
DatumSpecificationRecord DatumSpecificationRecord::LINKSIM_COMMENT_PDU(200612, "LINKSIM_COMMENT_PDU");
DatumSpecificationRecord DatumSpecificationRecord::NSST_OWNSHIP_CONTROL(200613, "NSST Ownship Control");
DatumSpecificationRecord DatumSpecificationRecord::OTHER(240000, "Other");
DatumSpecificationRecord DatumSpecificationRecord::MASS_OF_THE_VEHICLE(240001, "Mass Of The Vehicle");
DatumSpecificationRecord DatumSpecificationRecord::FORCE_ID_53(240002, "Force ID");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_TYPE_KIND(240003, "Entity Type Kind");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_TYPE_DOMAIN(240004, "Entity Type Domain");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_TYPE_COUNTRY(240005, "Entity Type Country");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_TYPE_CATEGORY(240006, "Entity Type Category");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_TYPE_SUB_CATEGORY(240007, "Entity Type Sub Category");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_TYPE_SPECIFIC(240008, "Entity Type Specific");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_TYPE_EXTRA(240009, "Entity Type Extra");
DatumSpecificationRecord DatumSpecificationRecord::ALTERNATIVE_ENTITY_TYPE_KIND(240010, "Alternative Entity Type Kind");
DatumSpecificationRecord DatumSpecificationRecord::ALTERNATIVE_ENTITY_TYPE_DOMAIN(240011, "Alternative Entity Type Domain");
DatumSpecificationRecord DatumSpecificationRecord::ALTERNATIVE_ENTITY_TYPE_COUNTRY(240012, "Alternative Entity Type Country");
DatumSpecificationRecord DatumSpecificationRecord::ALTERNATIVE_ENTITY_TYPE_CATEGORY(240013, "Alternative Entity Type Category");
DatumSpecificationRecord DatumSpecificationRecord::ALTERNATIVE_ENTITY_TYPE_SUB_CATEGORY(240014, "Alternative Entity Type Sub Category");
DatumSpecificationRecord DatumSpecificationRecord::ALTERNATIVE_ENTITY_TYPE_SPECIFIC(240015, "Alternative Entity Type Specific");
DatumSpecificationRecord DatumSpecificationRecord::ALTERNATIVE_ENTITY_TYPE_EXTRA(240016, "Alternative Entity Type Extra");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_LOCATION_X(240017, "Entity Location X");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_LOCATION_Y(240018, "Entity Location Y");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_LOCATION_Z(240019, "Entity Location Z");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_LINEAR_VELOCITY_X(240020, "Entity Linear Velocity X");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_LINEAR_VELOCITY_Y(240021, "Entity Linear Velocity Y");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_LINEAR_VELOCITY_Z(240022, "Entity Linear Velocity Z");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_ORIENTATION_PSI(240023, "Entity Orientation Psi");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_ORIENTATION_THETA(240024, "Entity Orientation Theta");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_ORIENTATION_PHI(240025, "Entity Orientation Phi");
DatumSpecificationRecord DatumSpecificationRecord::DEAD_RECKONING_ALGORITHM(240026, "Dead Reckoning Algorithm");
DatumSpecificationRecord DatumSpecificationRecord::DEAD_RECKONING_LINEAR_ACCELERATION_X(240027, "Dead Reckoning Linear Acceleration X");
DatumSpecificationRecord DatumSpecificationRecord::DEAD_RECKONING_LINEAR_ACCELERATION_Y(240028, "Dead Reckoning Linear Acceleration Y");
DatumSpecificationRecord DatumSpecificationRecord::DEAD_RECKONING_LINEAR_ACCELERATION_Z(240029, "Dead Reckoning Linear Acceleration Z");
DatumSpecificationRecord DatumSpecificationRecord::DEAD_RECKONING_ANGULAR_VELOCITY_X(240030, "Dead Reckoning Angular Velocity X");
DatumSpecificationRecord DatumSpecificationRecord::DEAD_RECKONING_ANGULAR_VELOCITY_Y(240031, "Dead Reckoning Angular Velocity Y");
DatumSpecificationRecord DatumSpecificationRecord::DEAD_RECKONING_ANGULAR_VELOCITY_Z(240032, "Dead Reckoning Angular Velocity Z");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_APPEARANCE(240033, "Entity Appearance");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_MARKING_CHARACTER_SET(240034, "Entity Marking Character Set");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_MARKING_11_BYTES(240035, "Entity Marking 11 Bytes");
DatumSpecificationRecord DatumSpecificationRecord::CAPABILITY(240036, "Capability");
DatumSpecificationRecord DatumSpecificationRecord::NUMBER_ARTICULATION_PARAMETERS(240037, "Number Articulation Parameters");
DatumSpecificationRecord DatumSpecificationRecord::ARTICULATION_PARAMETER_ID(240038, "Articulation Parameter ID");
DatumSpecificationRecord DatumSpecificationRecord::ARTICULATION_PARAMETER_TYPE_54(240039, "Articulation Parameter Type");
DatumSpecificationRecord DatumSpecificationRecord::ARTICULATION_PARAMETER_VALUE_55(240040, "Articulation Parameter Value");
DatumSpecificationRecord DatumSpecificationRecord::TYPE_OF_STORES(240041, "Type Of Stores");
DatumSpecificationRecord DatumSpecificationRecord::QUANTITY_OF_STORES(240042, "Quantity Of Stores");
DatumSpecificationRecord DatumSpecificationRecord::FUEL_QUANTITY(240043, "Fuel Quantity");
DatumSpecificationRecord DatumSpecificationRecord::RADAR_SYSTEM_STATUS(240044, "Radar System Status");
DatumSpecificationRecord DatumSpecificationRecord::RADIO_COMMUNICATION_SYSTEM_STATUS(240045, "Radio Communication System Status");
DatumSpecificationRecord DatumSpecificationRecord::DEFAULT_TIME_FOR_RADIO_TRANSMISSION_FOR_STATIONARY_TRANSMITTERS(240046, "Default Time For Radio Transmission For Stationary Transmitters");
DatumSpecificationRecord DatumSpecificationRecord::DEFAULT_TIME_FOR_RADIO_TRANSMISSION_FOR_MOVING_TRANSMITTERS(240047, "Default Time For Radio Transmission For Moving Transmitters");
DatumSpecificationRecord DatumSpecificationRecord::BODY_PART_DAMAGED_RATIO(240048, "Body Part Damaged Ratio");
DatumSpecificationRecord DatumSpecificationRecord::NAME_OF_THE_TERRAIN_DATABASE_FILE(240049, "Name Of The Terrain Database File");
DatumSpecificationRecord DatumSpecificationRecord::NAME_OF_LOCAL_FILE(240050, "Name Of Local File");
DatumSpecificationRecord DatumSpecificationRecord::AIMPOINT_BEARING(240051, "Aimpoint Bearing");
DatumSpecificationRecord DatumSpecificationRecord::AIMPOINT_ELEVATION(240052, "Aimpoint Elevation");
DatumSpecificationRecord DatumSpecificationRecord::AIMPOINT_RANGE(240053, "Aimpoint Range");
DatumSpecificationRecord DatumSpecificationRecord::AIR_SPEED(240054, "Air Speed");
DatumSpecificationRecord DatumSpecificationRecord::ALTITUDE_56(240055, "Altitude");
DatumSpecificationRecord DatumSpecificationRecord::APPLICATION_STATUS(240056, "Application Status");
DatumSpecificationRecord DatumSpecificationRecord::AUTO_IFF(240057, "Auto Iff");
DatumSpecificationRecord DatumSpecificationRecord::BEACON_DELAY(240058, "Beacon Delay");
DatumSpecificationRecord DatumSpecificationRecord::BINGO_FUEL_SETTING(240059, "Bingo Fuel Setting");
DatumSpecificationRecord DatumSpecificationRecord::CLOUD_BOTTOM(240060, "Cloud Bottom");
DatumSpecificationRecord DatumSpecificationRecord::CLOUD_TOP(240061, "Cloud Top");
DatumSpecificationRecord DatumSpecificationRecord::DIRECTION(240062, "Direction");
DatumSpecificationRecord DatumSpecificationRecord::END_ACTION(240063, "End Action");
DatumSpecificationRecord DatumSpecificationRecord::FREQUENCY(240064, "Frequency");
DatumSpecificationRecord DatumSpecificationRecord::FREEZE(240065, "Freeze");
DatumSpecificationRecord DatumSpecificationRecord::HEADING(240066, "Heading");
DatumSpecificationRecord DatumSpecificationRecord::IDENTIFICATION_57(240067, "Identification");
DatumSpecificationRecord DatumSpecificationRecord::INITIAL_POINT_DATA(240068, "Initial Point Data");
DatumSpecificationRecord DatumSpecificationRecord::LATITUDE_58(240069, "Latitude");
DatumSpecificationRecord DatumSpecificationRecord::LIGHTS_59(240070, "Lights");
DatumSpecificationRecord DatumSpecificationRecord::LINEAR(240071, "Linear");
DatumSpecificationRecord DatumSpecificationRecord::LONGITUDE_60(240072, "Longitude");
DatumSpecificationRecord DatumSpecificationRecord::LOW_ALTITUDE(240073, "Low Altitude");
DatumSpecificationRecord DatumSpecificationRecord::MFD_FORMATS(240074, "Mfd Formats");
DatumSpecificationRecord DatumSpecificationRecord::NCTR(240075, "Nctr");
DatumSpecificationRecord DatumSpecificationRecord::NUMBER_PROJECTILES(240076, "Number Projectiles");
DatumSpecificationRecord DatumSpecificationRecord::OPERATION_CODE(240077, "Operation Code");
DatumSpecificationRecord DatumSpecificationRecord::PITCH(240078, "Pitch");
DatumSpecificationRecord DatumSpecificationRecord::PROFILES(240079, "Profiles");
DatumSpecificationRecord DatumSpecificationRecord::QUANTITY_61(240080, "Quantity");
DatumSpecificationRecord DatumSpecificationRecord::RADAR_MODES(240081, "Radar Modes");
DatumSpecificationRecord DatumSpecificationRecord::RADAR_SEARCH_VOLUME(240082, "Radar Search Volume");
DatumSpecificationRecord DatumSpecificationRecord::ROLL(240083, "Roll");
DatumSpecificationRecord DatumSpecificationRecord::ROTATION_62(240084, "Rotation");
DatumSpecificationRecord DatumSpecificationRecord::SCALE_FACTOR_X(240085, "Scale Factor X");
DatumSpecificationRecord DatumSpecificationRecord::SCALE_FACTOR_Y(240086, "Scale Factor Y");
DatumSpecificationRecord DatumSpecificationRecord::SHIELDS(240087, "Shields");
DatumSpecificationRecord DatumSpecificationRecord::STEERPOINT(240088, "Steerpoint");
DatumSpecificationRecord DatumSpecificationRecord::SPARE1(240089, "Spare1");
DatumSpecificationRecord DatumSpecificationRecord::SPARE2(240090, "Spare2");
DatumSpecificationRecord DatumSpecificationRecord::TEAM(240091, "Team");
DatumSpecificationRecord DatumSpecificationRecord::TEXT(240092, "Text");
DatumSpecificationRecord DatumSpecificationRecord::TIME_OF_DAY(240093, "Time Of Day");
DatumSpecificationRecord DatumSpecificationRecord::TRAIL_FLAG(240094, "Trail Flag");
DatumSpecificationRecord DatumSpecificationRecord::TRAIL_SIZE(240095, "Trail Size");
DatumSpecificationRecord DatumSpecificationRecord::TYPE_OF_PROJECTILE(240096, "Type Of Projectile");
DatumSpecificationRecord DatumSpecificationRecord::TYPE_OF_TARGET(240097, "Type Of Target");
DatumSpecificationRecord DatumSpecificationRecord::TYPE_OF_THREAT(240098, "Type Of Threat");
DatumSpecificationRecord DatumSpecificationRecord::UHF_FREQUENCY(240099, "Uhf Frequency");
DatumSpecificationRecord DatumSpecificationRecord::UTM_ALTITUDE(240100, "Utm Altitude");
DatumSpecificationRecord DatumSpecificationRecord::UTM_LATITUDE(240101, "Utm Latitude");
DatumSpecificationRecord DatumSpecificationRecord::UTM_LONGITUDE(240102, "Utm Longitude");
DatumSpecificationRecord DatumSpecificationRecord::VHF_FREQUENCY(240103, "Vhf Frequency");
DatumSpecificationRecord DatumSpecificationRecord::VISIBILITY_RANGE(240104, "Visibility Range");
DatumSpecificationRecord DatumSpecificationRecord::VOID_AAA_HIT(240105, "Void Aaa Hit");
DatumSpecificationRecord DatumSpecificationRecord::VOID_COLLISION(240106, "Void Collision");
DatumSpecificationRecord DatumSpecificationRecord::VOID_EARTH_HIT(240107, "Void Earth Hit");
DatumSpecificationRecord DatumSpecificationRecord::VOID_FRIENDLY(240108, "Void Friendly");
DatumSpecificationRecord DatumSpecificationRecord::VOID_GUN_HIT(240109, "Void Gun Hit");
DatumSpecificationRecord DatumSpecificationRecord::VOID_ROCKET_HIT(240110, "Void Rocket Hit");
DatumSpecificationRecord DatumSpecificationRecord::VOID_SAM_HIT(240111, "Void Sam Hit");
DatumSpecificationRecord DatumSpecificationRecord::WEAPON_DATA(240112, "Weapon Data");
DatumSpecificationRecord DatumSpecificationRecord::WEAPON_TYPE(240113, "Weapon Type");
DatumSpecificationRecord DatumSpecificationRecord::WEATHER_63(240114, "Weather");
DatumSpecificationRecord DatumSpecificationRecord::WIND_DIRECTION_64(240115, "Wind Direction");
DatumSpecificationRecord DatumSpecificationRecord::WIND_SPEED(240116, "Wind Speed");
DatumSpecificationRecord DatumSpecificationRecord::WING_STATION(240117, "Wing Station");
DatumSpecificationRecord DatumSpecificationRecord::YAW(240118, "Yaw");
DatumSpecificationRecord DatumSpecificationRecord::MEMORY_OFFSET(240119, "Memory Offset");
DatumSpecificationRecord DatumSpecificationRecord::MEMORY_DATA(240120, "Memory Data");
DatumSpecificationRecord DatumSpecificationRecord::VASI(240121, "VASI");
DatumSpecificationRecord DatumSpecificationRecord::BEACON(240122, "Beacon");
DatumSpecificationRecord DatumSpecificationRecord::STROBE(240123, "Strobe");
DatumSpecificationRecord DatumSpecificationRecord::CULTURE(240124, "Culture");
DatumSpecificationRecord DatumSpecificationRecord::APPROACH(240125, "Approach");
DatumSpecificationRecord DatumSpecificationRecord::RUNWAY_END(240126, "Runway End");
DatumSpecificationRecord DatumSpecificationRecord::OBSTRUCTION(240127, "Obstruction");
DatumSpecificationRecord DatumSpecificationRecord::RUNWAY_EDGE(240128, "Runway Edge");
DatumSpecificationRecord DatumSpecificationRecord::RAMP_TAXIWAY(240129, "Ramp Taxiway");
DatumSpecificationRecord DatumSpecificationRecord::LASER_BOMB_CODE(240130, "Laser Bomb Code");
DatumSpecificationRecord DatumSpecificationRecord::RACK_TYPE(240131, "Rack Type");
DatumSpecificationRecord DatumSpecificationRecord::HUD(240132, "HUD");
DatumSpecificationRecord DatumSpecificationRecord::ROLEFILENAME(240133, "RoleFileName");
DatumSpecificationRecord DatumSpecificationRecord::PILOTNAME(240134, "PilotName");
DatumSpecificationRecord DatumSpecificationRecord::PILOTDESIGNATION(240135, "PilotDesignation");
DatumSpecificationRecord DatumSpecificationRecord::MODEL_TYPE(240136, "Model Type");
DatumSpecificationRecord DatumSpecificationRecord::DIS_TYPE(240137, "DIS Type");
DatumSpecificationRecord DatumSpecificationRecord::CLASS(240138, "Class");
DatumSpecificationRecord DatumSpecificationRecord::CHANNEL(240139, "Channel");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_TYPE_65(240140, "Entity Type");
DatumSpecificationRecord DatumSpecificationRecord::ALTERNATIVE_ENTITY_TYPE_66(240141, "Alternative Entity Type");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_LOCATION(240142, "Entity Location");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_LINEAR_VELOCITY(240143, "Entity Linear Velocity");
DatumSpecificationRecord DatumSpecificationRecord::ENTITY_ORIENTATION(240144, "Entity Orientation");
DatumSpecificationRecord DatumSpecificationRecord::DEAD_RECKONING(240145, "Dead Reckoning");
DatumSpecificationRecord DatumSpecificationRecord::FAILURE_SYMPTOM(240146, "Failure Symptom");
DatumSpecificationRecord DatumSpecificationRecord::MAX_FUEL(240147, "Max Fuel");
DatumSpecificationRecord DatumSpecificationRecord::REFUELING_BOOM_CONNECT(240148, "Refueling Boom Connect");
DatumSpecificationRecord DatumSpecificationRecord::ALTITUDE_AGL(240149, "Altitude AGL");
DatumSpecificationRecord DatumSpecificationRecord::CALIBRATED_AIRSPEED(240150, "Calibrated Airspeed");
DatumSpecificationRecord DatumSpecificationRecord::TACAN_CHANNEL(240151, "TACAN Channel");
DatumSpecificationRecord DatumSpecificationRecord::TACAN_BAND(240152, "TACAN Band");
DatumSpecificationRecord DatumSpecificationRecord::TACAN_MODE(240153, "TACAN Mode");


DatumSpecificationRecord::DatumSpecificationRecord(int value, std::string description) :
  Enumeration(value, description)
{
  enumerations[value] = this;
};

DatumSpecificationRecord* DatumSpecificationRecord::findEnumeration(int aVal) {
  DatumSpecificationRecord* pEnum;

  enumContainer::iterator enumIter = enumerations.find(aVal);
  if (enumIter == enumerations.end()) pEnum = NULL;
  else pEnum = (*enumIter).second;
  return pEnum;
};

std::string DatumSpecificationRecord::getDescriptionForValue(int aVal) {
  DatumSpecificationRecord* pEnum = findEnumeration(aVal);
  if (pEnum) return pEnum->description;
  else {
    std::stringstream ss;
    ss <<  "Invalid enumeration: " << aVal;
    return (ss.str());
  }
};

DatumSpecificationRecord DatumSpecificationRecord::getEnumerationForValue(int aVal) throw(EnumException) {
  DatumSpecificationRecord* pEnum = findEnumeration(aVal);
  if (pEnum) return (*pEnum);
  else  {
    std::stringstream ss;
    ss << "No enumeration found for value " << aVal << " of enumeration DatumSpecificationRecord";
    throw EnumException("DatumSpecificationRecord", aVal, ss.str());
  }
};

bool DatumSpecificationRecord::enumerationForValueExists(int aVal) {
  DatumSpecificationRecord* pEnum = findEnumeration(aVal);
  if (pEnum) return (true);
  else       return (false);
};

DatumSpecificationRecord::enumContainer DatumSpecificationRecord::getEnumerations() {
  return (enumerations);
};

DatumSpecificationRecord& DatumSpecificationRecord::operator=(const int& aVal) throw(EnumException)
{
	(*this) = getEnumerationForValue(aVal);
	return (*this);
};


}  /* namespace DIS */

